name: Continuous Integration
on:
  push:
    paths:
      - "**.cs"
      - "**.yml"
  pull_request:
    paths:
      - "**.cs"
      - "**.yml"

jobs:
  build-ubuntu:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: sudo apt-get update
      - run: sudo apt-get install mono-mcs
      - run: mcs parseops.cs
      - uses: actions/upload-artifact@master
        with:
          name: edopsparser-allplatforms
          path: parseops.exe

  create-release:
    needs: [build-ubuntu]
    runs-on: ubuntu-20.04
    if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/master'
    steps:
    - name: Download all phatforms artifact
      uses: actions/download-artifact@v1
      with:
        name: edopsparser-allplatforms

    - name: Prepare artifacts for release
      run: |
        7z a -tzip edopsparser-allplatforms.zip edopsparser-allplatforms/*

    - name: Create release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: "${{ contains(github.ref, '-rc') }}"
        files: |
          edopsparser-allplatforms.zip
